### ISSUE TITLE
Update desc documentation link to docs for latest version

### ISSUE THREAD

**Issue by DhruvDh** [kdy1/rweb#18]

**Comment by kdy1** [comment]
What do you mean? Did you mean docs.rs link should be included in Cargo.toml?
(I'm not an english native.)

**Comment by DhruvDh** [comment]
Sorry, should've elaborated. The description for this repository links to documentation of an outdated version of this crate on docs.rs

**Comment by kdy1** [comment]
Updated it. Thank you!!
