### ISSUE TITLE
dependency injection not possible?

### ISSUE THREAD

**Issue by vn971** [kdy1/rweb#39]
Hi. I'm trying to write an `rweb` API. The way I wanted to do it, is to use dependency injection to provide some parameters for the API layer. Something along the lines of:
```rust
pub struct ApiLayer {
  pub name: String,
  pub db: Database,
}

impl ApiLayer {
  #[get("/output")]
  fn output(&self) -> String {
      format!("Hello from api layer named {}", self.name)  // <------- problem here
  }

  pub async fn run_server(&self) {
    serve(...);
  }
}
```

The problem, however, is that the compiler complains with something like:
```txt
^^^^ `self` value is a keyword only available in methods with a `self` parameter
...
 this function doesn't have a `self` parameter
```
It would seem that the macro has eliminated the `self` parameter, and it is thus no longer available inside the method. If I comment out the `#[get("/output")]` line, things start to compile.

Question is: did I correctly interpret what's happening?
And follow-up: is there any work-around?

Thanks!

**Comment by PaulMaddox** [comment]
Did you find a workaround for this?

**Comment by vn971** [comment]
@PaulMaddox nope... I also encountered some other bugs (which I raised) when trying to use the OpenAPI feature. So I ended up going for warp.

**Comment by kdy1** [comment]
It can be fixed by adding a simple macro, but I'm too bust these days to fix it. Sorry for it.

**Comment by vn971** [comment]
@kdy1 that's great to hear! Not intending to be aggressive, just trying to answer the question or be technically detailed. I hope the project succeeds, would love to eventually see broader OpenAPI support!

**Comment by E-gy** [comment]
I believe this is (and [perhaps was at the time](https://github.com/kdy1/rweb/commit/1154e8140e1def1c89ef2b7429c20b0190f3cf24)) possible with [`#[data]`](https://docs.rs/rweb/0.12.4/rweb/#data).
It still doesn't work with `self`, but the end result is pretty much same.

Can this be considered resolved?

**Comment by kdy1** [comment]
I thinks so, thanks!

**Comment by vn971** [comment]
@E-gy @kdy1 I think `#data` solves the problem indeed! \o/ thanks
