### ISSUE TITLE
#[serde(rename_all)] doesn't applied to the enum variant name on openapi spec

### ISSUE THREAD

**Issue by HyeonuPark** [kdy1/rweb#44]
If I have an enum like below:

```rust
#[derive(Serialize, Deserialize, Schema)]
#[serde(rename_all = "camelCase")]
pub enum Name {
    Foo,
    Bar,
}
```

The generated spec contains `"enum": ["Foo", "bar"]`, not `"enum": ["foo", "bar"]`. Adding `#[serde(rename)]` to each variants works as expected though.

**Comment by kdy1** [comment]
Fixed and published a new version.
