### ISSUE TITLE
Error compiling macro module

### ISSUE THREAD

**Issue by szagi3891** [kdy1/rweb#46]
When I try to run rweb I get this compilation error:

```
MacBook-Pro-Grzegorz:notatki_panel grzegorzszeliga$ ./server_start.sh
    Updating crates.io index
    Updating git repository `https://github.com/vertigo-web/vertigo`
   Compiling proc-macro-nested v0.1.7
   Compiling tokio-util v0.3.1
   Compiling tempfile v3.2.0
   Compiling rweb-macros v0.4.5
   Compiling futures-util v0.3.11
error[E0432]: unresolved import `syn::export`
  --> /Users/grzegorzszeliga/.cargo/registry/src/github.com-1ecc6299db9ec823/rweb-macros-0.4.5/src/openapi/mod.rs:19:5
   |
19 |     export::ToTokens,
   |     ^^^^^^ could not find `export` in `syn`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rweb-macros`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
MacBook-Pro-Grzegorz:notatki_panel grzegorzszeliga$ 
```

Can I ask for help?

**Comment by dbanty** [comment]
This appears to be due to [this change](https://github.com/dtolnay/syn/commit/957840eba2c7f11c95e0227760d78dc481a91de7#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R790-R792) in syn. Apparently the export module was not supposed to be part of the public API so they removed it.

As far as I can tell there's no easy way to force cargo to downgrade syn to make it work for now 🙁

**Comment by kdy1** [comment]
Please upgrade rweb to 0.5.x

**Comment by dbanty** [comment]
I don't know about OP but I was getting this on the latest 0.5 with the openapi feature.

**Comment by kdy1** [comment]
Then I think cargo update will fix it.

**Comment by szagi3891** [comment]
I am using the latest version of this library:
```
warp = "0.2"
rweb = "0.5.4"
```

I wanted to start using this library on my site. The idea that this rweb library presents is fantastic. Very big compliments for the idea and implementation. 

But it worries me a little that the library is currently in such a state that it can't even compile.  This can be a little discouraging for new users.

**Comment by szagi3891** [comment]
@kdy1 Please reopen this issue as the problem has not been fixed.

**Comment by kdy1** [comment]
Fixed and published a new version.

**Comment by szagi3891** [comment]
Fantastic :) Thank you very much.
