### ISSUE TITLE
Upgrade to tokio 1?

### ISSUE THREAD

**Issue by ShadowJonathan** [kdy1/rweb#48]
Tokio [announced](https://tokio.rs/blog/2020-12-tokio-1-0) version one for itself lately? Maybe it's a good idea to upgrade support for this?

**Comment by ShadowJonathan** [comment]
(Maybe this includes upgrading warp to `0.3`)

**Comment by ddboline** [comment]
I opened a pull request to do just that: https://github.com/kdy1/rweb/pull/49
There were breaking changes for SSE, websockets and streams, but everything else works pretty well.
