### ISSUE TITLE
Error compiling example

### ISSUE THREAD

**Issue by ranaya-formant** [kdy1/rweb#53]
error[E0432]: unresolved import `syn::export`
  --> /home/skynet/.cargo/registry/src/github.com-1ecc6299db9ec823/rweb-macros-0.3.0-alpha.1/src/openapi.rs:19:5
   |
19 |     export::ToTokens,
   |     ^^^^^^ could not find `export` in `syn`

**Comment by kdy1** [comment]
Use lastest version
