### ISSUE TITLE
Implement openapi::Entity for chrono types

### ISSUE THREAD

**Issue by freopen** [kdy1/rweb#83]
Crate [chrono](https://docs.rs/chrono/0.4.19/chrono/) contains `chrono::Date` and `chrono::DateTime` structs that have `Serialize` and `Deserialize` [implemented to match](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#impl-Serialize) the [OAS formats](https://swagger.io/specification/#data-types) `date` and `date-time`. I wonder if it makes sense to have a default implementation of `rweb::openapi::Entity` for `chrono::Date` and `chrono::DateTime` so it's possible to use `#[derive(Schema)]` for structs that contain chrono types?

**Comment by kdy1** [comment]
Yes I think so, under a cargo feature.
