### ISSUE TITLE
Incorrect OpenAPI spec for Result type

### ISSUE THREAD

**Issue by freopen** [kdy1/rweb#87]
I'm very new to this, sorry if I misunderstood something. Minimal example is below:

```rust
#[derive(Serialize, Schema)]
enum MyError {
  CustomError,
}

#[get("/test_result")]
fn test_result() -> Json<Result<String, MyError>> {
  Json::from(Err(MyError::CustomError))
}
```

This filter returns following OpenAPI spec:
```json
{
   "openapi":"3.0.1",
   "info":{
      "title":"",
      "version":""
   },
   "paths":{
      "/test_result":{
         "get":{
            "responses":{
               "200":{
                  "description":"",
                  "content":{
                     "application/json":{
                        "schema":{
                           "oneOf":[
                              {
                                 "type":"string"
                              },
                              {
                                 "type":"string",
                                 "enum":[
                                    "CustomError"
                                 ]
                              }
                           ]
                        }
                     }
                  }
               }
            }
         }
      }
   }
}
```

However, running the code gives this output:

```json
{
  "Err": "CustomError"
}
```

Note that `serde-json` represents `Result` type as either `{"Ok": <T>}` or `{"Err": <E>}`.

Seems like the correct OpenAPI should be something like that:

```json
...
"schema": {
  "oneOf": [
    {
      "type": "object",
      "properties": {
        "Ok": {
          "type": "string"
        }
      }
    },
    {
      "type": "object",
      "properties": {
        "Err": {
          "type": "string",
          "enum": [
            "CustomError"
          ]
        }
      }
    }
  ]
}
...
```

**Comment by E-gy** [comment]
Indeed you are right. Current implementation always assumes that `#[serde(untagged)]` is applied to the enum (perhaps because in JS-realm externally tagged enums are rare).

So yeah, to fix this rweb will need to support detection of serde tagging attrs - absent (current implementation) vs internal (using OpenAPI `discriminator` prop) vs external (see OP).

**Comment by freopen** [comment]
There is a separate implementation for Result: https://docs.rs/rweb/0.12.3/src/rweb/openapi/entity.rs.html#507-528 and it seems that Result as a foreign type can only be used as an external tagging. So maybe it makes sense to adjust this part or temporarily `unimplemented!()` it as it's currently guaranteed to produce incorrect results.
