### ISSUE TITLE
Openapi specs are not generating when #[data] is in use

### ISSUE THREAD

**Issue by glebpom** [kdy1/rweb#90]
When #[data] is not used, specs are generating correctly

**Comment by E-gy** [comment]
Can you provide an example of where this happens?

(firing up one of my projects on rweb, that uses `#[data]` (and updating rweb), i am unable to reproduce the [mis]behaviour you described)

**Comment by glebpom** [comment]
Here is the example:

```
    #[allow(unused_mut)]
    #[get("/api/v1/accounts/{account_name}/projects/{project_name}/requests/{request_id}")]
    #[openapi(summary = "get log entry by request_id")]
    pub async fn request_info(
        account_name: AccountName,
        project_name: ProjectName,
        request_id: RequestId,
        #[filter = "authorization_filter"] authorization: Authorization,
        #[data] mut service: Service,
    ) -> Result<Json<serde_json::Value>, Rejection> {
     ...
    }

    ....

    let request_info_with_state = requests::request_info(service.clone());

    ....


    let (spec, filter) = openapi::spec().build(move || {
        regions_with_state
            .or(request_info_with_state)
            .or(invalidate_cache_with_state)
            .or(...)
    });

    ...

    rweb::serve(
          filter
              .or(openapi_docs(spec))
              .or(heathcheck_with_state)
              .or(metrics())
              .recover(handle_rejection),
      )
   
```

With this code, I don't see open API data generated

**Comment by E-gy** [comment]
This seems to have nothing to do with `#[data]` in particular, but with how `rweb`'s `openapi::spec().build` works. More specifically, in the example above, the filters are built _outside_ the `build` closure, which seems to be causing the issue.

Here's the gist to reproduce the bug, along with a comparison of usage of `build` (and thus a "fix" to have the API generated properly):
https://gist.github.com/E-gy/27358171b1b2abe0ce6b018e16dce7ea#file-main-rs-L67-L83

**Comment by glebpom** [comment]
Thanks! It works now
